### ISSUE TITLE
fails on windows with prerender: true

### ISSUE THREAD

**Issue by fooooooooooooooo** [vikejs/vike-cloudflare#29]
with a project created using `pnpm create bati --vue --cloudflare` and `prerender: true` in vike plugin config on windows, `pnpm run preview` fails with

```
[vike-cloudflare] ENOENT: no such file or directory, stat 'D:\vike-test\dist\D:\vike-test\dist\client\index.html'
```

the issue seems to be from using `path.posix.relative` with windows backslash paths

https://github.com/vikejs/vike-cloudflare/blob/043302866aa6a46bc47ffd2db291964cec7f2da8/packages/vike-cloudflare/src/index.ts#L150

at this point, `outClient` is `D:\vike-test\dist\client` and when calling `posix.relative` on a file path such as `D:/vike-test/dist/client/index.html`, it results in `../D:/vike-test/dist/client/index.html`, which is then joined with `outClient` again to create the insane `D:\vike-test\dist\D:\vike-test\dist\client\index.html`

a solution which seems to work for me is just using `path.relative` instead of `path.posix.relative` but i dont know if that might cause issues on other systems

**Comment by magne4000** [comment]
Thanks for the detailed issue. This is fixed in latest version!
